swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/monthly:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transactions for a specific month
      description: API to retrieve transactions for a specific month
      parameters:
        - name: year
          in: query
          description: Year
          type: integer
          required: true
        - name: month
          in: query
          description: Month
          type: integer
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Transactions for the specified month retrieved successfully
          schema:
            $ref: "#/definitions/TransactionOfMonth"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get a specific transaction
      description: API to retrieve a specific transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Create a new transaction with a specific ID
      description: API to create a new transaction with a specific ID
      parameters:
        - name: id
          in: path
          description: Transaction ID
          required: true
          type: string
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update a specific transaction
      description: API to update a specific transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID to update
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete a specific transaction
      description: API to delete a specific transaction
      parameters:
        - name: id
          in: path
          description: Transaction ID to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
          schema:
            $ref: "#/definitions/TransactionDelete"

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Transaction:
    type: object
    properties:
      category:
        type: string
        description: Transaction category
      transactionType:
        type: string
        description: Type of transaction
      note:
        type: string
        description: Additional notes about the transaction

  TransactionDelete:
    type: object
    properties:
      status:
        type: string
        description: The status of the transaction deletion
      messages:
        type: array
        items:
          type: string
        description: An array of messages related to the transaction deletion

  TransactionOfMonth:
    type: object
    properties:
      Id:
        type: string
        description: Unique identifier for the transaction
      date:
        type: number
        description: Date of the transaction
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Transaction balance

  
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
